#! /bin/sh

# sets up xrandr. Probably shouldn't hardcode this, but here we go.
~/at-home.sh

sxhkd &

nitrogen --restore

bspc monitor -d I II III IV

bspc config border_width         4
bspc config window_gap          16

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# This is an attempt to have fullscreen video stay in the node's sizing, but it
# gets the horizontal totally wrong. Looks like I can keep the default setting
# but use Mod-t, whatever that does.
# bspc config ignore_ewmh_fullscreen all
