[misc]
# This functionality is (currently? forever?) broken on Linux, so disable.
skip_notify = true

# Additional git repositories to pull
#git_repos = [
#    "~/src/*/",
#    "~/.config/something"
#]

# Disable specific steps - same options as the command line flag
#
# cargo - I believe this only updates things that were `cargo install`ed, which
# I don't do.
# chezmoi - I'm using jj and so the default command blows up. Also, I don't
# want it to auto-update my dotfiles, since I'm often tinkering with them
# locally.
# vim - I will decide when to update plugins
# gem/ruby_gem - It's not helpful, since it's either installing new versions of something that will be locked in Bundler, or upgrading super outdated Mac system Ruby. Unsure of the difference between these two, also.
disable = ["cargo", "asdf", "containers", "chezmoi", "vim", "gem", "ruby_gems"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass Git when pulling Repositories
#git_arguments = "--rebase --autostash"

# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"

# Do not set the terminal title
#set_title = false
# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
#[commands]
#"Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"

# Cleanup temporary or old files
#cleanup = true
